app_id: "some.value"
business_unit: "A Business"
product_name: "My product"
channel: "Web"
test_engineers: "Mr Tester"
document_1_title: "Test Plan"
document_1_url: "https://example.com"
document_2_title: "Sanity DataSheet"
document_2_url: "https://example.com"
